# Site settings
title: Adit Modi
twitter_username: rob_hinds
name: Adit Modi

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/robhinds
 - title: StackOverflow
   url: https://stackoverflow.com/users/258813/rhinds
 - title: DZone
   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
-AWS
-GCP
-Azure
-Hadoop
-Spark
-Cloud Computing
-python
-OCI
-Cloud Services
-Docker
-Kubernetes

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

# Work Experience

<ul>
<li><h4> Company Name : Atliq Technologies </h4> 
  <h4> Work Role : Software Development Engineer Intern</h4> 
  <h4> From : 2020-04 </h4> 
  <h4> to :2020-07 </h4> 
  <h4> Details :
Worked on large scale application based on PHP, Laravel and Javascript.
Migrating Data from on-premise to AWS Cloud .
Understanding the Project Infrastructure and Developing and Testing Functions by automating and streamlining the integration and deployment processes.
</h4> 
</li></ul>

<ul>
<li><h4> Company Name : Amazon Web Services. </h4> 
  <h4> Work Role : 	AWS Educate Student Ambassador </h4> 
  <h4> From : 2020-05 </h4> 
  <h4> present </h4> 
  <h4> Details :
The AWS Educate Student Ambassador Program gives AWS Educate student members recognition, access to career development opportunities, and other benefits for helping their peers learn about Amazon Web Services. 
</h4> 
</li></ul>


# Education


 - <h4>College Name: Dharmsinh Desai University</h4>
    
    <h4>Degree: Computer Science</h4>
    
    <h4>From:2017-07</h4>
    
    <h4>To: 2021-05</h4>
    
    <h4>About College: </h4>


#List of interesting Github repo/projects to include - optional
github:
 - robhinds/robhinds.github.io
 - robhinds/ScaLambda
 - robhinds/opinionated-akka-http
 - robhinds/food2vec
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/genotype
 - robhinds/footweets
 - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/258813/rhinds
   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
 
