# Site settings
title: Adit Modi
twitter_username: aditmodi24
name: Adit Modi

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://dev.to/aditmodi
 - title: GitHub
   url: https://github.com/aditmodi
 - title: Cloud Tech
   url: https://www.linkedin.com/company/68000829/admin/
 - title: LinkedIn
   url: https://www.linkedin.com/in/adit-modi/
 - title: Medium
   url: https://medium.com/@adit-modi24

#Any buzzword skills you want to include
skills:
- AWS
- GCP
- Azure
- Docker
- Kubernetes
- Terraform
- Linux
- Mongodb
- Nginx

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://dev.to/api/articles?username=aditmodi

#Work experience is required
roles:
 - title: AWS Community Builder
   start: 2021
   end: Ongoing
   employer: Amazon Web Services
   description: The AWS Community Builders program offers technical resources, mentorship, and networking opportunities to AWS enthusiasts and emerging thought leaders who are passionate about sharing knowledge and connecting with the technical community.
                My interest is primarily on AWS Storage . I'll be creating content to share with the wider tech community on making the most out of AWS services as a Cloud Engineer.
 - title: AWS Educate Cloud Ambassador
   start: 2020
   end: 2021
   employer: Amazon Web Services
   description:  • The AWS Educate Student Ambassador Program gives AWS Educate student members recognition, access to career development opportunities, and other benefits for helping their peers learn about Amazon Web Services.
                 • Building the AWS (India Region ) Cloud Community that hosts sessions and activities that deepen and equip scholars with AWS Cloud Computing skills and Big Data competencies.
                 • I have led a team of 15 students to complete the 12 AWS Cloud Career Pathway Certifications and 3 start-ups to secure the AWS Activate Credits, providing them with low cost, easy to use infrastructure for growth and scalability. 
 - title: Cloud Engineer
   start: 2021
   end: Ongoing
   employer: Digital-alpha
   description: 
 - title: Cloud Engineer Intern
   start: 2020
   end: 2021
   employer: Digital-Alpha
   description: • Solution building includes developing cloud infrastructure automation, cloud native applications, documentation, architecture diagrams, monitoring & support, operating manuals etc. ( Worked on Terraform and CI/CD Pipelines with AWS and Azure ) .
                • Maintain 24/7 up-time of demo-ready solutions in the cloud environment( Both AWS and Azure Environment) .
                • to build specific cloud-native solutions for targeted business problems and Improve the solution design and implementation by iterating and incorporate inputs .
 - title: 
   start: 2021
   end: 2021
   employer: 
   description: • Involved in Designing applications for Development , Monitoring developed applications and fixing bugs.
                • AWS - (EC2, RDS, S3, Route53, VPC, Security Groups, AMI, Cloud Formation, Cloud Front, Cloud Watch, Elastic Beanstalk, IAM, ECS and EKS ).
                • Server and associated technologies - Linux or Ubuntu .
                • Web and Application Server technologies - React , Angular , Node and Nginx .
                • DevOps, Orchestration/Configuration Management and Continuous Integration technology -  Docker, Jenkins, Webhook , Code Pipeline ( including codebuild and codedeploy ) and Kubernetes . scripting language - bash and Javascript . Networking OSI model (TCP/IP, DNS, HTTP, Routing)
                • Version control platform - git , github and bitbucket .
                • Database technologies - MongoDB, Mysql, SQl
                • Domain and SSL expertise - Godaddy, Google domain , Ionos , certbot and bitnami.
 - title: Software Engineer Intern
   start: 2020
   end: 2020
   employer: AtliQ Technologies 
   description: • Work under the guidance of leads to build specific cloud-native solutions for targeted business
                problems (Migrating Data from on-premise to Cloud Environment) .
                • Understanding the Project Infrastructure and Developing and Testing Functions by automating and streamlining the integration and deployment processes.
                • Improve the solution design and implementation by iterating and incorporate inputs from the leads and architects .

#Education is required
education:
 - level: Bachelor of Technology (B.Tech)
   date: 2021
   subject: Computer Science
   school: Dharmsinh Desai University

#This section is optional (as is the image link below)


#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute

#List of interesting Github repo/projects to include - optional
github:
# - robhinds/robhinds.github.io

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
      Hi , I'm Adit !! I am a final year Computer Science Undergrad Studying at Dharmsinh Desai University, Nadiad.<br/><br/>

      I am an cloud Enthusiast aspiring to be a solutions architect , I am passionate about creating solutions that not only solve problems but impact lives of people around us. I am currently focused on learning Devops automation while leveraging my knowledge of cloud services .<br/><br/>

      I spend my time exploring about multi-cloud solutions using different cloud services provided by cloud providers like Amazon Web Services, Microsoft Azure, Google Cloud Platform, Alibaba Cloud & Oracle Cloud Infrastructure.<br/><br/>

      I love to interact with people so please feel free to connect with me on linkedIn or follow me on medium / dev community .<br/><br/>
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   
